# Generated by Django 3.2.7 on 2022-01-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
