# Generated by Django 3.2.7 on 2021-10-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0002_auto_20211020_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
