# Generated by Django 3.1.1 on 2021-11-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0003_delete_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='buy_sell',
            field=models.CharField(blank=True, choices=[('+', 'Kupno'), ('-', 'Sprzedaz')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='visdata',
            name='shares_number',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=999, null=True),
        ),
    ]
