# Generated by Django 3.2.7 on 2021-12-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0004_auto_20211116_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicName',
            fields=[
                ('tic_id', models.AutoField(primary_key=True, serialize=False)),
                ('tic_sym', models.CharField(max_length=10)),
                ('tic_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
