# Generated by Django 3.2.7 on 2021-12-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0005_auto_20211202_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visdata',
            name='portfolio_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='optifolio.portfolio'),
        ),
    ]
