# Generated by Django 3.2.5 on 2021-11-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0005_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visdata',
            name='user_name',
        ),
        migrations.AddField(
            model_name='visdata',
            name='port_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optifolio.portfolio'),
        ),
    ]
