# Generated by Django 3.2.5 on 2021-11-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0006_auto_20211121_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visdata',
            name='port_id',
        ),
        migrations.AddField(
            model_name='visdata',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optifolio.customer'),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
