# Generated by Django 3.2.7 on 2021-12-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0006_alter_visdata_portfolio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visdata',
            name='portfolio_id',
        ),
        migrations.AddField(
            model_name='visdata',
            name='portfolio_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optifolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
