# Generated by Django 3.2.2 on 2021-12-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optifolio', '0005_ticname'),
        ('optifolio', '0007_auto_20211203_0923'),
    ]

    operations = [
    ]
